spring:
  application:
    name: ticket
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tiketatka;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/tiketatka?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
#    username: root
#    password:
  jpa:
    hibernate:
      ddl-auto: validate
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
  sql:
    init:
      schema-locations: classpath*:sql/schema.sql
      mode: always

springdoc:
  swagger-ui:
    path: /swagger-custom-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**

jwt:
  tokenExpirationSec: 1800
  refreshExpirationSec: 604800
  tokenIssuer: tiketatka
  base64TokenSigningKey: l8rSsOP9c5VhhhT3Rg2WAOhXnN4reW9NMaYqUFj11rmtqOSUE9AS