spring:
  application:
    name: ticket
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ticketaka?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true}
    username: root
    password: rootpassword
    hikari:
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    static-path-pattern: /static/**
  sql:
    init:
      mode: always
      schema-locations: classpath*:sql/schema.sql
      data-locations: classpath*:sql/data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope: openid,profile,email
          naver:
            client-id: ${NAVER_OAUTH_CLIENT_ID}
            client-secret: ${NAVER_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-name: ticketaka-dev
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope: profile,email
          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: ticketaka-dev
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname,profile_image,account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

springdoc:
  swagger-ui:
    path: /swagger-custom-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**

jwt:
  tokenExpirationSec: 1800
  refreshExpirationSec: 604800
  tokenIssuer: tiketatka
  base64TokenSigningKey: -hlsZR9K42niHhGXI4qhpeetTZ-MFC121DXl_MzFBq0
token:
  size: 200
  capacity: 200