spring:
  application:
    name: ticket
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ticketaka?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true}
    username: root
    password: rootpassword
    hikari:
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath*:sql/schema.sql
      data-locations: classpath*:sql/data.sql
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

springdoc:
  swagger-ui:
    path: /swagger-custom-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**

jwt:
  tokenExpirationSec: 1800
  refreshExpirationSec: 604800
  tokenIssuer: tiketatka
  base64TokenSigningKey: l8rSsOP9c5VhhhT3Rg2WAOhXnN4reW9NMaYqUFj11rmtqOSUE9AS
token:
  capacity: 100