version: '3.8'
services:
  app:
    depends_on:
      - app-db
    container_name: ticketaka-dev
    image: ticketaka-dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ticketaka?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    ports:
      - 8080:8080

