version: '3.8'
services:
  app:
    depends_on:
      - app-db
    container_name: ticketaka-dev
    image: ticketaka-dev
    environment:
      - JAVA_OPTS=-Xmx1200m -Xms1200m
    ports:
      - 8080:8080

