version: '3.8'
services:
  app:
    container_name: ticketaka-dev
    image: ticketaka-dev
    environment:
      - JAVA_OPTS=-Xmx1200m -Xms1200m
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8080:8080

