version: '3.8'

services:
  redis:
    image: redis:7.0.2
    container_name: redis
    env_file:
      - .env
    restart: always
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./config/redis/redis.conf:/etc/redis/redis.conf
      - redis-data:/data
    command: redis-server /etc/redis/redis.conf
volumes:
    redis-data:
        driver: local